import SiteFooter from "@/components/site-footer";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Disclaimer | alfamus.com",
  description:
    "Read the full disclaimer for alfamus.com. Understand the limitations of our job aggregation service, AI tools, and advertised content.",
};

export default function DisclaimerPage() {
  return (
    <div className="min-h-screen" style={{ backgroundColor: "#F8F6F1" }}>
      <div className="py-20" style={{ backgroundColor: "#0F1F3D" }}>
          <div className="container mx-auto px-4">
            <h1
              className="text-5xl font-bold text-white"
              style={{ fontFamily: "Fraunces, serif" }}
            >
              Disclaimer
            </h1>
            <p className="text-white/60 mt-3 text-lg">
              Last Updated: March 28, 2025
            </p>
          </div>
        </div>

        <div className="container mx-auto px-4 py-16 max-w-3xl">
          <div className="bg-white rounded-2xl border border-[#E8E4DC] p-8 space-y-8 text-gray-600 text-sm leading-relaxed">

            <section>
              <h2 className="text-xl font-bold text-[#0F1F3D] mb-3" style={{ fontFamily: "Syne, sans-serif" }}>
                1. General Disclaimer
              </h2>
              <p>
                The information provided on alfamus.com is for general informational and educational purposes only. While we make every effort to keep the information accurate, relevant, and up to date, we make no representations or warranties of any kind, express or implied, about the completeness, accuracy, reliability, suitability, or availability of the information, products, services, or related graphics contained on the website for any purpose.
              </p>
              <p className="mt-3">
                Any reliance you place on such information is therefore strictly at your own risk. In no event will alfamus Internet Pvt. Ltd., its directors, employees, partners, or affiliates be liable for any loss or damage including without limitation, indirect or consequential loss or damage, arising from the use of this website.
              </p>
            </section>

            <hr className="border-[#E8E4DC]" />

            <section>
              <h2 className="text-xl font-bold text-[#0F1F3D] mb-3" style={{ fontFamily: "Syne, sans-serif" }}>
                2. Job Listings Disclaimer
              </h2>
              <p>
                alfamus.com is a job aggregation platform. We collect job listings from publicly available sources including company career pages, job boards, and third-party APIs. We are <strong className="text-[#0F1F3D]">not a recruitment agency</strong> and do not represent any employer or job seeker.
              </p>
              <ul className="mt-3 space-y-2 list-disc list-inside">
                <li>We do not guarantee the accuracy, legality, or availability of any job listing.</li>
                <li>Job listings may be expired, inaccurate, or sourced from third parties we do not control.</li>
                <li>We are not responsible for the outcome of any job application or interview process.</li>
                <li>Listing on our platform does not constitute endorsement of any employer, company, or job opportunity.</li>
                <li><strong className="text-[#0F1F3D]">Never pay money to apply for a job.</strong> Fraudulent job offers may appear across the internet. Legitimate employers do not charge candidates for applications or training.</li>
              </ul>
            </section>

            <hr className="border-[#E8E4DC]" />

            <section>
              <h2 className="text-xl font-bold text-[#0F1F3D] mb-3" style={{ fontFamily: "Syne, sans-serif" }}>
                3. AI & Career Advice Disclaimer
              </h2>
              <p>
                alfamus.com provides an AI-powered career chatbot and general career content for informational purposes only. The advice, suggestions, and content generated by our AI tools:
              </p>
              <ul className="mt-3 space-y-2 list-disc list-inside">
                <li>Do NOT constitute professional legal, financial, HR, or career counseling advice.</li>
                <li>May not be accurate, complete, or appropriate for your individual circumstances.</li>
                <li>Are generated by AI models and may contain errors or outdated information.</li>
              </ul>
              <p className="mt-3">
                Always seek the advice of a qualified professional before making significant career, legal, or financial decisions. alfamus.com shall not be liable for any consequences arising from reliance on AI-generated advice.
              </p>
            </section>

            <hr className="border-[#E8E4DC]" />

            <section>
              <h2 className="text-xl font-bold text-[#0F1F3D] mb-3" style={{ fontFamily: "Syne, sans-serif" }}>
                4. Advertising Disclaimer
              </h2>
              <p>
                alfamus.com displays advertisements served through Google AdSense and may feature other forms of paid advertising. Please be aware of the following:
              </p>
              <ul className="mt-3 space-y-2 list-disc list-inside">
                <li>Advertisements are served automatically by Google and are not individually reviewed or endorsed by alfamus.com.</li>
                <li>We are not responsible for the content, products, or services advertised through our platform.</li>
                <li>Clicking on an advertisement will take you to a third-party website governed by its own terms and privacy policies.</li>
                <li>We receive compensation when ads are displayed or clicked. This supports the free services we provide.</li>
                <li>We do NOT engage in click fraud, invalid traffic generation, or any activity that violates Google AdSense policies.</li>
              </ul>
              <p className="mt-3">
                If you encounter an advertisement that you believe is misleading, harmful, or inappropriate, please report it via Google's ad feedback mechanism or email us at abuse@alfamus.com.
              </p>
            </section>

            <hr className="border-[#E8E4DC]" />

            <section>
              <h2 className="text-xl font-bold text-[#0F1F3D] mb-3" style={{ fontFamily: "Syne, sans-serif" }}>
                5. External Links Disclaimer
              </h2>
              <p>
                alfamus.com contains links to external websites that are not provided or maintained by us. We do not guarantee the accuracy, relevance, timeliness, or completeness of any information on these external websites.
              </p>
              <p className="mt-3">
                The inclusion of any link does not necessarily imply a recommendation or endorsement of the views expressed within them. We have no control over the nature, content, and availability of those sites.
              </p>
            </section>

            <hr className="border-[#E8E4DC]" />

            <section>
              <h2 className="text-xl font-bold text-[#0F1F3D] mb-3" style={{ fontFamily: "Syne, sans-serif" }}>
                6. Blog & Content Disclaimer
              </h2>
              <p>
                Blog articles, career guides, and other written content published on alfamus.com are intended for general educational purposes. Content may reflect the views of individual authors and does not constitute professional advice. Market conditions, salary data, and industry trends mentioned in our content may change over time. Always verify important data from official and authoritative sources.
              </p>
            </section>

            <hr className="border-[#E8E4DC]" />

            <section>
              <h2 className="text-xl font-bold text-[#0F1F3D] mb-3" style={{ fontFamily: "Syne, sans-serif" }}>
                7. No Endorsement
              </h2>
              <p>
                The mention of specific companies, employers, products, or services on alfamus.com does not constitute an endorsement or recommendation by alfamus Internet Pvt. Ltd. We do not vet or endorse individual employers or their hiring practices.
              </p>
            </section>

            <hr className="border-[#E8E4DC]" />

            <section>
              <h2 className="text-xl font-bold text-[#0F1F3D] mb-3" style={{ fontFamily: "Syne, sans-serif" }}>
                8. Changes to This Disclaimer
              </h2>
              <p>
                We reserve the right to update or modify this Disclaimer at any time. Changes will be reflected on this page with an updated date. Continued use of the Platform after any changes constitutes your acceptance of the updated Disclaimer.
              </p>
            </section>

            <hr className="border-[#E8E4DC]" />

            <section>
              <h2 className="text-xl font-bold text-[#0F1F3D] mb-3" style={{ fontFamily: "Syne, sans-serif" }}>
                9. Contact Us
              </h2>
              <p>
                If you have any questions about this Disclaimer or believe any content on alfamus.com is inaccurate or inappropriate, please contact us:
              </p>
              <ul className="mt-3 space-y-1">
                <li><strong className="text-[#0F1F3D]">Email:</strong> <a href="mailto:legal@alfamus.com" className="text-[#0D9488] hover:underline">legal@alfamus.com</a></li>
                <li><strong className="text-[#0F1F3D]">Abuse Reports:</strong> <a href="mailto:abuse@alfamus.com" className="text-[#0D9488] hover:underline">abuse@alfamus.com</a></li>
                <li><strong className="text-[#0F1F3D]">Contact Form:</strong> <a href="/contact" className="text-[#0D9488] hover:underline">alfamus.com/contact</a></li>
              </ul>
            </section>
          </div>
        </div>
      <SiteFooter />
    </div>
  );
}
